from collections.abc import Generator

class Xlsx:
    """Xlsx Reader / Writer"""

    def __init__(self, xlsx_file: str) -> None: ...
    def get_sheet_names(self) -> list[str]: ...
    def get_sheet_values(self, sheet_name: str) -> Generator[list[str], None, None]: ...
